### ISSUE TITLE
More gnulib files needed with recent m4 file updates.

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#1012]
I really should have included more of the ancillary files from gnulib with the recent m4 files. In the past I tried to get those in and they were rejected without a clear reason, so this time I left them out. But the new m4 files actually do reference some of them so we are getting warnings a autogen time. I'll create a new PR with those soon.

**Comment by tom95858** [comment]
@morrone, the reason the were not accepted is because it wasn't to clear me why they were "better" and I'm worried about local mods we have made to make our build work. If we are comfortable that the gnulib macros we are incorporating are better for whatever reason and will not regress our build, then it seems logical that we take them.

**Comment by tom95858** [comment]
@morrone, I think we've resolved this issue with your latest pull requests...or is there more to do here?

**Comment by morrone** [comment]
Yes, fixed by PR #1014. Thanks!
