### ISSUE TITLE
Python3 & RHEL 8 support incomplete.

### ISSUE THREAD

**Issue by andyw-lala** [ovis-hpc/ovis#131]
RHEL8 completely removes "python" by default, and instead provides "python2" and "python3".

Attempts to build master (@ ae2ac623) fail in interesting ways.

Big problem is that with our current minimal requirement in various configure.ac files:

```
configure.ac:        AM_PATH_PYTHON([2.6])
ldms/configure.ac:   AM_PATH_PYTHON(2.6)
lib/configure.ac:    AM_PATH_PYTHON([2.6], , [:])
```

_[side point: do we really need 3 styles ?]_

I am not really interested in building on RHEL8 using Python 2, since it is EOL.

But given those requirements, autoconf will always find python2 first.

Simply changing these to 3.6 (which I understand may not be acceptable to all, it was just a local test) results in the following error:

```
# ../configure --prefix=/opt/ldms --enable-swig
checking for gcc... gcc
...
configure: Enable swig module requested
checking for swig... /usr/bin/swig
checking for python... no
configure: error: Cannot find python in your system path
configure: error: ../../ldms/configure failed for ldms
```

So clearly something around the swig support is hardcoding python

Looking for a discussion on the best path forward to ensure that we pick up python3 if it is present, preferring that over python 2.x. Then consistently using the discovered python throughout.

I believe that using alternatives to map "python" onto python3 is a bad idea, even when RHEL do not provide a naked python.

Disclaimer: I'm not an autoconf person, and the google-fu is weak with me on this.

**Comment by andyw-lala** [comment]
Adding PYTHON_VERSION=3 to the environment is at least one trick to get past that.

It seems odd to me that the discovery of python3 is not passed to ldms/configure.

I plan to keep hacking until I get a version that builds, installs and works, then I can back out and theorize about the minimal/sensible set of changes required to get there.

**Comment by tom95858** [comment]
Hi @andyw-lala thanks for the test build.

We are moving all things python to Python3 as discussed at the UG meeting. Unfortunately, we haven't gotten to that yet.

**Comment by tom95858** [comment]
We will follow up with a schedule shortly.

**Comment by andyw-lala** [comment]
Ah - I clearly misunderstood - so Python3 support is incomplete/non-functional at present ?
I was laboring under the impression it was there, just not the default.

Shoot - that makes working on any RHEL8 platform problematic, since it forces your hand in this area.

Maybe I will backpedal on my assertion that I did not want to spend cycles getting ldms/python2 functional by installing enough legacy packages...

**Comment by baallan** [comment]
@andyw-lala we have cut the number of configure.ac scripts from 3 down to 1 on the OVIS-4 branch. That patch was not landed at the time of the 4.3.3 release.
We have not had a detailed discussion (afai recall) about whether the 4.x branch and releases will be updated to python3 or python3-only ldms will begin with the next major ldms release.

My personal feeling is that since it appears python 3.6.8 is available in rhel7 as python3, we could go ahead with a patch to the ovis-4 branch.  This might break some 3rd party python utilities if anyone has them, and it appears cython is missing for python3 in rhel7 so ldms-consistent SOS python3 support might be a problem for rhel7. 

An approach we have taken locally (for sandia testbeds) is to package ldms, cython, numpy, sos all as 'software collections' following the redhat standard. In that work, we still used the system python 2.7 but used recent(ish) cython and numpy. We could extend that work to have a python3 numpy/cython/sos/ldms software collection.

**Comment by morrone** [comment]
Did you check EPEL for cython?

**Comment by baallan** [comment]
There are numerous alternatives for non-redhat/non-TOSS-supported python, none delightful.
OGC is in the process of porting & testing master/v5 to entirely python3.

The real problem to be cracked is to have a TOSS-supported python>=3.6+new-enough-cython+new-enough-pandas. Apparently rhel8/TOSS3/TOSS4 has not taken on the challenge of making modern python available, except in the form of "run your own container and install anaconda (with all its potential security problems)".
