### ISSUE TITLE
ldmsd_failover.c v4(possibly v5) __ASSERT use need revision

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#231]
There are many asserts in ldmsd_failover of the form (NULL = "msg") where msg is not unique and not very informative at each location. Given that failover is expected to be a production feature in 4.3.4, these messages need to be made:

- rather more informative should the daemon crash, or
- into log messages, or
- (logic allowing) removed.

to be system administrator friendly.

**Comment by valleydlr** [comment]
Hi @baallan, 

asserts are _not_ meant for administrators. They are meant for developers. Please contact the developer directly, not the community at large if you think the messages they wrote for their own diagnostic purposes are inaccurate, insufficient or otherwise inappropriate.

On this site, in this context, the issues section should be used for manifest problems; symptomatic software behaviors that can be reproduced and addressed.
