### ISSUE TITLE
Top level package name change?

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#271]
On the OVIS-4 branch, the name of the package has changed from "ovis" to "ovis-ldms". The master branch still has the top level package named "ovis". Is this intentional? Is the master branch just lagging some changes from OVIS-4?

Just to be clear when I say "name of the package", I am referring to the name in AC_INIT in the top level configure.ac file. 

I want to double check that the new "ovis-ldms" is the intended long term name, because this has implications for things like the name of the tarball (ovis-ldms-<version>.tar.gz instead of the previous ovis-<version>.tar.gz). In turn, the names of the rpm packages will change as well, and I'm working on finalizing our OVIS 4 packages now.

**Comment by baallan** [comment]
The atse rpms layered above toss are currently named:

ovis (umbrella install package-- no code)
ovis-papi (papi library dependency for ldms syspapi plugin in $ovis_libdir/ovis-ldms/papi)
ovis-ldms-plugins-llnl (llnl lustre plugins for install in $ovis_libdir/ovis-ldms)
ovis_ldms (ldmsd)

The _ in ovis_ldms package name is due to the fact that using - instead breaks the rhel7 software collection naming convention that allows us to package for /opt or /usr with a collection spec file and the standard scl macros.

So there's no reason to tie rpm names directly to source code package names.

I would be fine with renaming ovis-ldms to ovis_ldms in the ac_init.

master is not tracking OVIS-4 build scripts currently, since it's a huge refactoring of directory structures and code. It would not be unreasonable to expect that eventually master will adopt some of the evolving details from ovis-4.

**Comment by morrone** [comment]
> So there's no reason to tie rpm names directly to source code package names.

Sure there is. Matching the rpm package name to the software it is packing is just good practice. It avoids confusing the heck out of people. There may be times when the package name must be changed (and maybe there are good reasons for whatever atse is), but the default plan should always be to have them match.

> I would be fine with renaming ovis-ldms to ovis_ldms in the ac_init.

Please don't. I certainly did not request that.

> master is not tracking OVIS-4 build scripts currently, since it's a huge refactoring of directory structures and code. It would not be unreasonable to expect that eventually master will adopt some of the evolving details from ovis-4.

I hope it is not unreasonabe to expect that there won't be any releases from that branch (except maybe pre-releases) until master catches up. We probably won't want to move from v4 to master until master catches up.

None of that really addressed my basic question. I am just going to work on the assumption that the ovis-ldms name is here to stay, and master will get the change at some point as all the changes are ported forward.
