### ISSUE TITLE
Malformed input on json stream causes ldmsd sampler to abort with assertion failure

### ISSUE THREAD

**Issue by eric-roman** [ovis-hpc/ovis#275]
A mismatched type sent on a stream to the slurm sampler causes ldmsd to abort with an assertion in v4.3.3.

Problem can be reproduced with
```
echo "{'event':1,'timestamp':2}" | ldmsd_stream_publish -a munge -x sock -h localhost -p 410 -s slurm -t json
```

Afterwards I see the following in the logs:
```
Jun 04 09:20:40 gert01 ldmsd[38407]: ldmsd: json_util.c:387: json_value_str: Assertion `value->type == JSON_STRING_VALUE' failed.
Jun 04 09:20:40 gert01 systemd[1]: ldmsd.sampler.service: Main process exited, code=killed, status=6/ABRT
```

**Comment by tom95858** [comment]
Hi @eric-roman, it was considered an application error to ask for a string when it's an int. The logic of that decision was that there is no reasonable value to return if the types don't match.

The infrastructure does check if the JSON syntax is well-formed, however, it can't check if the schema matches what the subscribers are expecting. Subscribers do schema checking to make certain that required attributes are present, here's an example of vulnerable subscriber code.

```C
       if (stream_type != LDMSD_STREAM_JSON) {
                msglog(LDMSD_LDEBUG, "papi_sampler: Unexpected stream type data...ignoring\n");
                msglog(LDMSD_LDEBUG, "papi_sampler:" "%s\n", msg);
                return EINVAL;
        }

        event = json_attr_find(entity, "event");
        if (!event) {
                msglog(LDMSD_LERROR, "papi_sampler: 'event' attribute missing\n");
                goto out_0;
        }

        json_str_t event_name = json_value_str(json_attr_value(event));  <-- crashes

```

...given that arbitrary user 'tom' can send a JSON string with an expected attribute name, but an unexpected attribute type is _very_ bad...

Here are a few options to consider:

1. Remove all the asserts...and cross our fingers
1. Add extensive type checking in the subscribers to ensure that the type of all the attributes is what is expected before asking for the value
1. Modify _type_ json_value_ _type_ (json_entity_t e) API to be _int_ json_value_ _type_ (json_entity_t, _type_ *val). If the entity type, don't match EINVAL is returned, otherwise, 0
1. Do 3, and add a new API _int_ json_attr_value_ _type_(json_entity_t e, const char *name, _type_ *val)

Personally, I like 4. because the subscriber code will be much more concise, e.g.

```C
       int rc;
       if (stream_type != LDMSD_STREAM_JSON) {
                msglog(LDMSD_LDEBUG, "papi_sampler: Unexpected stream type data...ignoring\n");
                msglog(LDMSD_LDEBUG, "papi_sampler:" "%s\n", msg);
                return EINVAL;
        }
        json_str_t event_name;
        rc = json_attr_value_str(entity, "event", &event_name);
        if (rc) {
                msglog(LDMSD_LERROR, "papi_sampler: 'event' attribute missing or invalid\n");
                goto out_0;
        }
```
