### ISSUE TITLE
annotated tag for PACKAGE_VERSION?

### ISSUE THREAD

**Issue by oceandlr** [ovis-hpc/ovis#313]
current version (504063) shows as PACKAGE_VERSION  UNKNOWN

From Commit 8b6dfc message:
    The LDMS project just needs to begin using annotated tags for its
    version tags to work with this change. Right now the version will
    show as "UNKNOWN" until an annotated tag is created at a previous
    version.

The current version does not have such a tag apparently. What is the policy on doing the annotated tags?
@tom95858 @morrone

**Comment by morrone** [comment]
I think people agreed to using annotated tags in a recent LDMS meeting.  Someone with write access to the repo needs to make it happen. One possibility would be replacing the OVIS-4.3.3 tag with one of the same name that is annotated.

**Comment by baallan** [comment]
I recall no such agreement and this just breaks current package scripting/adds extra work.
I propose we just add to autogen.sh if we are stuck with this change:

git tag -a $(current branch)-$(short-sha) $(short-sha) -m "$short-sha"

to have sensible default behavior. (where the proper incantations will have set short-sha and current-branch in proper shell syntax. This will get us $VERSION-$sha

**Comment by baallan** [comment]
@oceandlr to enable continue progress toward the snl DST next week,
I have tagged OVIS-4 with annotated OVIS-4.3.4 since it did not already have one.
./autogen.sh; ./configure; make dist
now produces ovis-ldms-4.3.4.tar.gz 
This fixes things to work again by default; packagers can add tags locally during packaging if they want a sha included or anything else.

**Comment by oceandlr** [comment]
Thanks, @baallan. Seems like it would be good to get a consensus on this issue, soon.

**Comment by morrone** [comment]
> I recall no such agreement and this just breaks current package scripting/adds extra work.
> I propose we just add to autogen.sh if we are stuck with this change:

@baallan Whoa. How does this add extra work? Creating the first annotated tag in the ovis repo was a one-time task.

Tagging releases is a normal part of the release process that already needs to be done. In the future, folks simply need to add the "-a" option to the "git tag" command that they already need to run.

If anything this would appear to _save_ a bit of work, because the previous process required additional file changes and commits (editing the version in configure.ac) to make a release. That step is no longer necessary. So that is actually less work no?

Plus this now allows workflows like mine (and others have the same requirement) in which the things we build and install for testing are now correctly, uniquely, and automatically versioned. So that saves work for those workflows. My TOSS release process also employs this, saving work there.

> git tag -a $(current branch)-$(short-sha) $(short-sha) -m "$short-sha"
> 
> to have sensible default behavior. (where the proper incantations will have set short-sha and current-branch in proper shell syntax. This will get us $branch-$short-sha

I confused about why you think that. This should not be necessary at all once the repo contains a annotated tag in the history. We should not make such a change to the autogen.sh.

And as @oceandlr pointed out, I fully documented the requirement to add that initial tag in my PR. I'm sorry for the short term inconvenience this has introduced. I have requested the use of annotated tags through github issues, LDMS meetings, and direct person email to ovis developers many times over the past year. I am not sure how I could have made this transition any smoother, but I'm completely open to advice on how that could have been easier.

I am also happy to explain anything that is unclear about this approach and how to work with. If you have questions, I am happy to help.

**Comment by morrone** [comment]
> @oceandlr to enable continue progress toward the snl DST next week,
> I have tagged OVIS-4 with annotated OVIS-4.3.4 since it did not already have one.

There was not yet an OVIS-4.3.4 tag because, to the best of my knowledge, OVIS version 4.3.4 has not yet been released. You have effectively just created the version 4.3.4 release. Was that your intent? Perhaps it would be better to remake the 4.3.3 tag? Or make a 4.3.4 alpha/beta/release canadidate tag instead of the final 4.3.4 tag?

**Comment by baallan** [comment]
@morrone you make a valid point that the tag name might mislead someone into thinking there was a release, though a quick look at the releases page or branches would correct that notion. Is it fair game to delete that tag and create an OVIS-4.3.4-dev annotated tag? Or is deleting a tag going to somehow break anyone who cloned it?

**Comment by baallan** [comment]
@morrone how is anything labeled with manually applied tags automatically correctly and uniquely versioned? I don't see a sha popping out in the version with this new scheme, so it's certainly not uniquely versioned unless you clone/checkout the tagged version instead of the branch.

It appears we need a documented refinement in our dev/tag/release processes if we're going to use a git hook in autogen which looks back an arbitrary distance to the most recent tag on the branch in use. Using the example of OVIS-4 current state,
- (various gyrations about 4.3.3 alpha/beta)
- tag/branch/release 4.3.3 from OVIS-4
- immediately tag the OVIS-4 branch with a new annotated tag OVIS-4.3.4-dev
- (code/test/swear,repeat)
- tag/release 4.3.4-alpha
- (code/test/swear,repeat)
- tag/release 4.3.4-beta
- (code/test/swear,repeat)
- tag/branch/release 4.3.4 from OVIS-4
- immediately tag the OVIS-4 branch with a new annotated tag OVIS-4.3.5-dev

Does that satisfy your needs?

**Comment by morrone** [comment]
It is reasonable to delete the tag from the repo. People who have fetched the tag already will need to delete the tag in their own repos to make it go away for them. If they don't then git fetch may complain about a conflict when they try to fetch the tag that will be created in the future. But I think folks probably will just have to deal with it at this point.

To delete the branch from the repo would would use a command like:

```git push origin :OVIS-4.3.4```

I would recommend that OVIS-4.3.4-dev is not the name we want either. We need, our versions to be versioned. So We might do something like "OVIS-4.3.4-alpha.0"

I still like the idea of replacing the OVIS-4.3.3 lightweight tag with an annotated tag. Something like this:

```
git tag -a -m "Tag OVIS-4.3.3" OVIS-4.3.3 e7530cc
git push origin :OVIS-4.3.3
git push origin OVIS-4.3.3
```

**Comment by baallan** [comment]
The problem we have is that the ovis-4 branch is not just a minor bugfix development, since the configure.ac version number was bumped to 4.3.4. There were major incompatibilities going from 4.2 to 4.3 and are by now minor (non-network) ones going from 433 to 434. Maybe if we did a 4.3.4.alpha0 back at the first commit that also included 4.3.4 as the version number we would get to a reasonable place. 

I prefer -dev to -alpha.0 until we're ready for arbitrary users (not our dev partners) to start testing development code. But that's something we should discuss as a group (what do alpha, beta, dev, unqualified) mean? I was looking for a page about the release process in our wiki and didn't find it, though I know there was powerpoint about it at the last ldmscon.

**Comment by morrone** [comment]
> @morrone how is anything labeled with manually applied tags automatically correctly and uniquely versioned? I don't see a sha popping out in the version with this new scheme, so it's certainly not uniquely versioned unless you clone/checkout the tagged version instead of the branch.

git-version-gen absolutely automatically generates unique versions. It just uses a value very similar to what "git describe" creates. I think that is maybe where you are confused. The "git describe" command (and git-version-gen) will use the unadulterated tag if your HEAD and the tag point to the same commit.  So you are probably seeing that happen and just assuming that it _never_ adds information. That is not the case at all.

In all other cases when your HEAD points to a commit _beyond_ the tag, then there will be other information appended to the previous tag to uniquely identify this commit.

Try it. Create a test commit or two beyond the tag and run autogen.sh, and build as normal. I am confident that it will work as I have described. I didn't even invent this; this script comes straight from the autoconf people designed for git.

> It appears we need a documented refinement in our dev/tag/release processes if we're going to use a git hook in autogen which looks back an arbitrary distance to the most recent tag on the branch in use. Using the example of OVIS-4 current state,
> 
> * (various gyrations about 4.3.3 alpha/beta)
> * tag/branch/release 4.3.3 from OVIS-4

We had already agreed previously to stop making branches every time there is a release. That doesn't really provide value. All we need is the tag. OVIS-4.3.3 almost got it right, except that folks forgot to make it an annotated tag.

**Comment by morrone** [comment]
> I prefer -dev to -alpha.0 until we're ready for arbitrary users (not our dev partners) to start testing development code. But that's something we should discuss as a group (what do alpha, beta, dev, unqualified) mean? I was looking for a page about the release process in our wiki and didn't find it, though I know there was powerpoint about it at the last ldmscon.

-dev to -alpha is not a progression that will be understood by a computer. Most packaging systems will think that -dev is newer than -alpha, rather that the other way around. That's a royal pain. Please don't go that route.

alpha is plenty well understood to be not ready for arbitrary users. People generally understand that "alpha" means that it is a development release, and it is still so unstable and untested that it can't even be called "beta" yet.

**Comment by tom95858** [comment]
@baallan, please delete the 4.3.4 tag. There is a large set of commits adding set reference counting and fixing scalability issues on uGNI. All of this is undergoing testing. My written notes document the agreement to use annotated tags at the LDMS UG.

**Comment by baallan** [comment]
@tom95858 please share your written notes/ppt re the tags/releases/naming process so I can get them (distilled if so advised) into the wiki.

Is it acceptable that i tag 4.3.4.alpha.0 at the point where you bumped the version in configure.ac to 4.3.4?

**Comment by baallan** [comment]
bad tag deleted.

**Comment by morrone** [comment]
It looks like we stalled inches from the goal line. We still need that annotated tag somewhere in the history of the OVIS-4 branch.

**Comment by baallan** [comment]
@morrone @tom95858 since no one has commented on my proposed tag for 3 days, I will make it this evening.
And I will propose to bump it from alpha.0 to alpha.1 when Tom's ovsi-4-ref-test changes finally get merged.

**Comment by tom95858** [comment]
@baallan: OVIS-4-alpha.0 is that right? @morrone, is there some syntax to the message that @baallan needs to adhere to?

**Comment by morrone** [comment]
It would be OVIS-4.3.4-alpha.0. Because presumably the next release will be 4.3.4, and this is a very early, unstable development, pre-release of 4.3.4.

There is no specific syntax required for the message. You can put any useful information that you think people should know about that tag. Later the OVIS-4.3.4 tag's message might look more like release nodes, or a summary of the release notes.

**Comment by baallan** [comment]
@oceandlr @morrone @tom95858  I have tagged OVIS-4.3.4-alpha.0 on the ovis-4 branch, so a clean clone, ./autogen.sh && configure && make dist now creates ovis-ldms-4.3.4-alpha.0.87-50406.tar.gz.
