### ISSUE TITLE
ldms_set_new() does not allow reuse of names previously relinquished by ldms_set_delete()

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#32]
This is a break-out of an issue that I encounted in issue #20.

It appears that ldms_set_delete() is not fully deleting all of the state from a metric set.  If one creates a metric set with name "A" using ldms_set_new(), then deletes that set with ldms_set_delete(), and then tries to create a new set with the name "A" using ldms_set_new(), the last metric set creation will fail.

In other words, metric set names cannot be reused.  It would appear that ldms_set_delete() is not fully deleting the metric set.

**Comment by tom95858** [comment]
If there are any RBD (Remote Buffer Descriptors) on the set, it is not deleted. This has been fixed in a development tree and should be part of 4.2.2.

**Comment by morrone** [comment]
@tom95858, that is great!  Would that fix also work for v3?  Can you share the branch on github?

**Comment by morrone** [comment]
Ping.  Can I see the v4 patch, or get a fix for v3/

**Comment by morrone** [comment]
I started looking at the v3 code, and it looks like there are a couple of bugs in ldms_set_delete(), one that the ->meta pointer is not freed, and another that the set is never removed from the global rbt under any condition.  Looking at the v4 rc branch, it looks like those are both already fixed.  So I imagine that I'll be able to fix those in v3 as well and submit the pull request for that.

After those are fixed, there will still remain that sometimes there will still be cleanup issues when the set->remote_rbd_list is not empty.  That sounds like the issue that is fixed somewhere that I can't see for v4.

Then again, the v3 goes on to free() the set unconditionally regardless of whether the remote_rbd_list was empty and the set was unpublished, so I suspect that things are left in a bad state in general.

I'll have to read and understand a bit more about the remote_rbd_list symantics, but perhaps forceably cleaning up that list is the right thing to do in v3.

**Comment by tom95858** [comment]
Hi @morrone. Unfortunately, these are not bugs; they are design limitations. The RBD are "remote buffer descriptors". By definition, if there is one on the list, then there is some client, remote or local, that refers to this set. If you were to blow away the list, you would have a client of the set pointing to garbage and use-after-free would occur.

The zap_share() call is how a peers gain access to each others memory. The RBD is the container that holds this data that says either "this is the key I gave my peer", or "this is the key the peer gave me". The key is used to RDMA from one peer to another.

Unfortunately, in 4.2.1 and prior, there is no zap_unshare() and therefore, there is no way to release the RBD. Even though the peer sends you DIR_DEL when it unregisters the set, short of disconnecting from the peer, there's no way to tell the peer to release the RBD.

So that is a long-winded way of saying that the fix is neither trivial, nor something you would want to back-port to v3.

**Comment by morrone** [comment]
Any update on which v4 release will have this fix?

**Comment by valleydlr** [comment]
v4.3 will have this fix. We will be starting testing on v4.3 this week and will roll out when it is determined to be stable.

**Comment by morrone** [comment]
This was fixed as of 4.3.3.

**Comment by baallan** [comment]
but see also 309. apparently there are more issues to reuse than just the input filter.

**Comment by morrone** [comment]
@baallan, thanks for the heads up, but #309 is the PR "Variable subdir v4". Did you mean some other issue?

**Comment by baallan** [comment]
@morrone just a poor indirection to the 'variable' test which recycles set name and tests the chain to storage with it.
ldms-static-test.sh variable
is showing symptoms.

**Comment by morrone** [comment]
@baallan could you please open a new issue to document the types of symptoms you are seeing, so I can follow along?
