### ISSUE TITLE
OVIS-4.3.4-alpha.1 tag is broken

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#326]
@tom95858 , you'll notice that your tag generated a failed action in https://github.com/ovis-hpc/ovis/actions.  

  https://github.com/ovis-hpc/ovis/actions/runs/176299355

Not only won't the OVIS-4.3.4-alpha.1 tag work with the "Create Release" workflow script, it won't work with the git-version-tag script either, so nothing built at this tag or later will even know that the OVIS-4.3.4-alpha.1 tag even exists.

**You did not use an annotated tag.**

All you need to do to make an annotated tag is to add the "-a" option to the "git tag" command. You'll be prompted to add a message as well. I don't care what you put in the message. But I would suggest the info that you manually put in https://github.com/ovis-hpc/ovis/releases.

If you had done that and used an annotated tag, when you pushed the tag to github, the release would have automatically been created, and the message from the tag would have been the message used on the release page.

Now we either need you to recreate the OVIS-4.3.4-alpha.1 as an annotated tag, or maybe just make a new OVIS-4.3.4-alpha.2 tag that points to the same commit. I honestly have no idea if the Create Release workflow will work since you manually created the release instead letting the script do it automatically. So maybe creating the OVIS-4.3.4-alpha.2 _annotated_ tag is the way to go.

The only thing that you might then need to do manually on the Release page is switch the release to a "pre-release".

In the future I could update the create-release.yaml file to automatically set "pre-release" true or false based on certain patterns in the tag name (contains, alpha or beta, for example).

**Comment by baallan** [comment]
@morrone that's odd.
when I clone OVIS-4 / autogen / configure /make dist I get out:
ovis-ldms-4.3.4.15-a16bb.tar.gz
so maybe a bug in a script?

**Comment by morrone** [comment]
> @morrone that's odd.
> when I clone OVIS-4 / autogen / configure /make dist I get out:
> ovis-ldms-4.3.4.15-a16bb.tar.gz
> so maybe a bug in a script?

@baallan, I do not think that is the case. You almost certainly did not do a fresh clone from the ovis-hpc/ovis.git repository. The version "4.3.4.15-a16bb" tells me that you are at commit a16bb, and that is 15 commits beyond a tag named "OVIS-4.3.4" in your local repo. The only annotated tag with name "OVIS-4.3.4" that I am aware of is the one that you created recently. That tag was removed from ovis-hpc/ovis.git, which is why I suspect that you did not do a clean clone of the repo. You are probably using an existing local git repo in which you forgot to delete the OVIS-4.3.4 tag.

And the reason the version did not start with "4.3.4-alpha.1" is, as I explained in the opening comment, because OVIS-4.3.4-alpha.1 is _not_ an annotated tag.

**Comment by baallan** [comment]
@morrone you are right. retry still sees alpha.0 and some dist omissions.

**Comment by tom95858** [comment]
Hi @morrone,

I used the github create release 'process' to generate the tag. I mistakenly assumed that since it had a message that it was an annotated tag. 

I have since done this:

git push --delete origin OVIS-4.3.4-alpha.1
git tag -a OVIS-4.3.4-alpha.1 -F stuff
git push origin OVIS-4.3.4-alpha.1

I'm not sure what you are expecting,  but it did not create a make dist tarball like I think you were expecting. The release page didn't look particularly nice either.

Undeterred, I did this in my repo:

git checkout -b OVIS_4.3.4-alpha.1 origin OVIS-4.3.4-alpha.1
sh autogen.sh
mkdir build
cd build
../configure
make dist

What I got was ovis-ldms-4.3.4-alpha.1.tar.gz

It seems that it is missing the git hash like I was expecting. It is an annotated tag, but there must be some piece of the puzzle that I am missing.

Also @baallan, I get warnings from the new function ovis_strerrorr. Seems like this should be cleaned up.

.libs/util.o: In function `ovis_strerror':
/home/tom/work/ovis-pkg/ovis/build/lib/src/ovis_util/../../../../lib/src/ovis_util/util.c:958: warning: `sys_errlist' is deprecated; use `strerror' or `strerror_r' instead
/home/tom/work/ovis-pkg/ovis/build/lib/src/ovis_util/../../../../lib/src/ovis_util/util.c:957: warning: `sys_nerr' is deprecated; use `strerror' or `strerror_r' instead

I have since deleted the tag and will play around with github to see if I can create an annotated tag through the GUI, but I followed the github annotated tag instructions last time and your claim is that it is not annotated. Perhaps there is some checkbox I neglected to click.

**Comment by tom95858** [comment]
@morrone: After recreating the tag and pushing it, the workflow was correctly triggered and the release was generated. The tar file generated, however, does not have the git hash. This matches my experience building it myself.

**Comment by baallan** [comment]
@tom95858 #278 introduced ovis_strerror so we can contain/avoid the strerror api insanities (thread incorrectness, potential memory leaks).
The "warning: sys_errlist' is deprecated; use strerror' or strerror_r' " is a nuisance warning from gnu ld. There is apparently nothing to be done to suppress it (I tried).
From the commented code I added:
 * If we truly hate it (the warning), we can use the code from nginx ngx_strerror
 * here. See: http://nginx.org/en/docs/sys_errlist.html
 * for why this is a good idea.

Any place else that we use strerror or strerror_r I will eventually make a patch to replace it (which will clean up a lot of strerror_r induced gyrations). Trying to focus on release testing for now though.

**Comment by tom95858** [comment]
lt's fine @baallan, if there is not alternative so be it. Not a big deal...just a nuisance like you said.

**Comment by morrone** [comment]
> @morrone: After recreating the tag and pushing it, the workflow was correctly triggered and the release was generated. The tar file generated, however, does not have the git hash. This matches my experience building it myself.

That is exactly how it should operate. It is not supposed to contain a git hash, because the commit is directly pointed to by an annotated tag. We only need additional information appended if the commit you are on is untagged or if your local repo is dirty (there are uncommitted changes to tracked files). When that happens, you will get a version string that starts with the most recent annotated tag in the repo and then appends additional information to the string to signal how the build is different from that past tag.

You will find this is very similar to how the "git describe" command works. So you can just play with changes to your repo and run git describe, and that will help you understand what is going on.

**Comment by tom95858** [comment]
Ok @morrone, thanks for the clarification; then we can claim success.

**Comment by tom95858** [comment]
@morrone, please close if everyone is happy.
