### ISSUE TITLE
Genders keywords for support for LDMS v4.x features

### ISSUE THREAD

**Issue by aamirrashid** [ovis-hpc/ovis#347]
We are porting LDMS Samplers from v3.x to v4.x. As we move towards configuration, I have some questions regarding "genders" that we use for configuration.

As we are testing our stuff, using straight text files outside of "genders",  we've had to introduce new "keywords" for configuration such as follows:

**DMSD Set Group**

    **Create set group** “setgroup_add name=" GROUP_NAME " [producer=" PRODUCER "] [interval=" USEC "]"
    **Modify set group** “setgroup_mod "name=" GROUP_NAME " [interval=" USEC "] [offset=" USEC "]"
    **Delete set group** “setgroup_del "name=" GROUP_NAME”
    **Insert set into group** “setgroup_ins "name=" GROUP_NAME " instance=" COMMA_SEPARATED_LIST_OF_INSTANCES”
    **Remove set from group** “setgroup_rm "name=" GROUP_NAME " instance=" COMMA_SEPARATED_LIST_OF_INSTANCES”

Auto Interval/Offset

When configuring the aggregator:

    "updtr_add name=policy2_h2 interval=10000000 offset=0 **auto_interval=true**"

Procdiskstats Sampler

    "config name=cray_procdiskstats producer=ldms2 instance=ldms2/cray_procdiskstats schema=cray_iostat **group=cray_proc_group**"

Would the "old" version of "genders" support the newly introduced keywords (in bold) listed above? If not, where would we find the new compatible version of "genders" for configuration of LDMS?

Thanks,
-aamir

**Comment by baallan** [comment]
@aamirrashid If this issue is still of interest, please comment. If not please let us know so we can close it.

Generally, regarding v4 genders:
- maestro (yaml-based) configuration is intended to replace genders. As such, minimal patches to genders support are being made. Major new syntax such as set-groups will only be supported in maestro.
- As with v3, the v4 genders-based systemd scripts include various 'trap-doors' and hooks to enable inserting script fragments which control features not handled with gender values.

**Comment by aamirrashid** [comment]
Hi Jim,

I've forwarded this msg to the new team within that owns LDMS now. 
Someone from that team will get in touch with you shortly.

Thanks,
-aamir
