### ISSUE TITLE
clean up installed /etc (sysconfdir)

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#366]
The following locations in the ldms build reference sysconfdir. Review what is installed in sysconfdir vs in /usr/share in all these makefiles.

./lib/etc/ovis/Makefile.am
./lib/etc/ld.so.conf.d/Makefile.am
./ldms/src/ldmsd-samplers/slurm/spank/Makefile.am
./ldms/src/ldmsd-samplers/aries_mmr/aries_mmr_set_configs/Makefile.am
./ldms/src/core/Makefile.am
./ldms/src/auth/Makefile.am
./ldms/etc/Makefile.am
./ldms/etc/systemd/Makefile.am
./ldms/etc/logrotate.d/Makefile.am
./ldms/etc/init.d/Makefile.am

**Comment by baallan** [comment]
@valleydlr @morrone I made an issue to remind us to review /etc usage.

**Comment by oceandlr** [comment]
Please x-ref with pull request and issue #314. Some items were moved  out of /etc into /share/<...>/examples as part of that.

**Comment by baallan** [comment]
Also, since the addition of the git version string to AC_INIT in configure.ac, the directory $docdir/$PACKAGE_VERSION has become harder to work with at packaging time and isn't really buying us anything as we typically package.
I propose we switch from what I started in ldms v2 ($docdir/$PACKAGE_VERSION) back to the gnu default ($docdir/$PACKAGE).

I suppose it could still be useful to keep the doc version suffixed path if we were to encourage configure/package usages such as:
  ./configure --program-suffix=-434
much as python is often installed with suffix 2 or suffix 3 on 'bin/python'.
I think I would prefer to just document that we are not supporting program-suffix/program-prefix, and leave the nightmare of co-installs-to-the-same-prefix to packagers who cannot live without it.

**Comment by morrone** [comment]
It is not clear to me why PACKAGE_VERSION would now be harder to work with at packaging time. It hasn't cause me any issues with packaging (and on the contrary makes some things much better come packaging time). But that is not the main issue.

I think moving to just the autoconf standard @docdir@ would be fine. I don't see any clear reason for appending a version to the doc directory. ldms is not like python. Python versions _everything_ about the install, which is why the doc directory also has a version. For instance, there are separate "python2" and "python3" binaries, and the libraries are all separated into different versioned path.  LDMS doesn't do that.

I am not aware of a good use case for versioning just the doc directory in ldms, so I think we can just eliminate this without needing to add a "--program-suffix".

**Comment by baallan** [comment]
@tom95858 I believe this has all been fixed for the default case.

If a builder/packager requests non-default --enable-etc, the etc dir build will try to write on /etc unless the builder sets DESTDIR at build time or redefines sysconfdir at configure time.

For the above reasons, I'm closing the issue.
A separate discussion should be had about moving the /etc/ installed example files to readthedocs.io or a testing environment or the man pages. Several of the files installed apply only to XC40, for example.
