### ISSUE TITLE
apparent leaks of memory and/or locks in v4

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#369]
Probable leaks in or near the control path  identified with static analysis are noted in the commit of 
 WIP: review apparent v4 leaks request #263 . These need to be fixed, proved false positive (which I could not when trying), or identified as replaced with revised code.

**Comment by tom95858** [comment]
HI @baallan, I don't think WIP, in general belongs in a pull request. That's why I closed it.

That said, thank you for re-posting as an issue, however, issues is not a place to assign work to others. If you want these warnings to be resolved then:
* Figure out what's going on and propose a code change with associated test claims about how it resolved the symptom experienced, or
* Provide the log files from the static analysis tool along with some statement of risk and hope that some kind soul will feel compelled to resolve it for you

Absent the above, this is a claim of unspecified symptoms of unspecified harm with an unspecified solution.

**Comment by baallan** [comment]
@tom95858 @valleydlr  The harm (repeated memory leaks) is specified precisely in the WIP commit associated with #263. I didn't assign anything to anyone, I merely reported apparent, specific resource leaks in a system daemon.  They happen to be in portions of the code in which I am not an expert. If noone cares to look into it prior to announcing a release as production ready, I will not worry myself about it further. 

As time permits, I may be able to find the raw audit log that points at the annotated locations. I suspect it should be mailed to someone rather than posted here, but let me know your preferences.
