### ISSUE TITLE
Distcheck failed on OVIS-4.3.4 release

### ISSUE THREAD

**Issue by tom95858** [ovis-hpc/ovis#462]
@morrone, did I mess this up somehow? I used the create release feature of github, but it seems to have failed the distcheck test.

**Comment by morrone** [comment]
"distcheck" is just in the comment of the commit on the head of the branch. It didn't actually have anything to do with the failure.

The failure was in the "Create Release" workflow, and it was because you didn't use an annotated tag for the release. Please get in the habit of using annotated tags.
