### ISSUE TITLE
Why is logging function passed to plugin through a function pointer?

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#48]
Is there any reason that an ldms sampler plugin could not simply use ldmsd_msg_logger() directly instead of using the function pointer that is passed to the sampler through get_plugin()?

Using the exported symbol directly is much preferable to a plugin implementer when they are using multiple files in their plugin for organizational purposes.  Using the function pointer, combined with the ldmsd rule that all globals must be file-scope in samplers results in unnecessary cruft in the code.

**Comment by baallan** [comment]
I proposed an ovis logging library (olog) in ldms v2 (and the code is still in the tree) so that main and plugins would have equal access to the logging symbols via a library. It was rejected at the time. The log functions are in the file with main, which isn't highly portable, so we pass them by pointer currently.
