### ISSUE TITLE
ldms_ls default arguments not supported by ldmsctl

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#523]
ldms_ls [-a $auth_plugin] works for localhost/sock/411, but ldmsctl does not.

Is this just a shortage of 'round tuits' (in which case, I can look at fixing it), or is there some design intent that ldmsctl should force the command line user to be explicit about host, etc.?

**Comment by nichamon** [comment]
@baallan ldmsctl 's -h option has no default values. Actually, ldmsctl has no default values for all command-line options, except for the -a option. This behavior is intended so that it has the same behavior as ldmsd_controller. I'm not against ldmsctl and ldmsd_controller having the same default values as ldms_ls's -x, -h and -p options. However, IMO, it is unnecessary to add default values now as our top priority is to stabilize OVIS-4.3.4 and this is not a bug.
