### ISSUE TITLE
Questions on SLURM samplers

### ISSUE THREAD

**Issue by weijianwen** [ovis-hpc/ovis#533]
I found multiple SLURM-related samplers in OVIS, say `job_info`, `job_info_slurm` and `slurm`. How should choose between them? And is any of them capable of briefing SLURM, for example, number of pending/running jobs?

Thank you!

**Comment by tom95858** [comment]
job_info - this an ldmsd sampler.
* It reads from a file, parses the file contents and populates an ldms metric set with job data.
* It uses inotify to awaken when the file it is configured to read is written
** Note that if the file is written multiple times, the sampler will awaken and attempt to parse it after every write. Care must be taken to write the input file with consistent data, all at "once"
* This sampler is not slurm specific, i.e. the file format is independent of the scheduler in use

job_info_slurm - this is a slurm spank plugin
* Implements the various slurm callback events
* Writes  relatively limited Job information to a file that presumably an ldmsd is watching for modifications

slurm - an ldmsd sampler
* Subscribes to an ldmsd stream
* Updates an ldmsd metric set based on the data published on the stream
** Includes job start, end, name, rank data, pid for each rank, etc...
* Supports multiple jobs per node, i.e. a multi-tenant system
* Despite it's name, it is not slurm specific. Any job scheduler publishing data in the expected stream format is supported.

spank - A spank plugin
* Implements the various slurm callback functions
* Supports multiple jobs per node
* Publishes data to an ldmsd stream
* Publishes job start, end, name, user data, rank and pid/rank information
** This is used by some plugins (e.g. papi) to attach performance events to process id

So that's the overview. In general slurm/spank are preferred because:
* The sampler can run on any aggregator in the infrastructure provided that the spank plugin has network connectivity to that node
* Is not subject to the partial write/consistency issues with a file
* Supports multi-tenancy
* Includes rank/pid and other detailed job information that is not present in the other samplers

**Comment by baallan** [comment]
@weijianwen Tom left out the older jobid sampler; job_info is mostly a better replacement for it, but jobid is still usable for single-user-per-node situations and it collects a bit less data.
