### ISSUE TITLE
Set ipmisensors is inconsistent.

### ISSUE THREAD

**Issue by MAChenliang** [ovis-hpc/ovis#585]
Hi,I got a problem when I tried to store the data from ipmisensors sampler.

I tried to use the store_csv and timescale-store.FinalIy,I got the same log output : Set cas200/ipmisensors is inconsistent.

```
load name=ipmisensors
config name=ipmisensors producer=${MYHOST} instance=${MYHOST}/ipmisensors component_id=${COMPONENT_ID} address=localhost
start name=ipmisensors interval=${SAMPLE_INTERVAL} offset=${SAMPLE_OFFSET}
```

**Comment by tom95858** [comment]
@MAChenliang, the store will not store metric-set data in the 'inconsistent' state because it implies that the metrics in the metric set were gathered at different times.

A metric set has a flag "inconsistent" that means that the set is in the process of being updated. If you look at the ipmisensors sampler, this is the logic in between the ldms_transaction_begin() and ldms_transaction_end() calls in the sampler's _sample_ method.

Possible causes include:

- The time it is taking to gather the IPMI sensors is "very long", i.e. a significant percentage of the sample interval,
- The sampler is stuck (i.e. blocked) in the sample code

Specific actions you might take is to look at whether or not the metric set is _ever_ in the consistent state at the compute node. I'm guessing that it's not and that the thread that is attempting to gather the IPMI data is 'stuck'.

**Comment by MAChenliang** [comment]
@tom95858 ,thanks for your answer.

I observed that ipmisensors set has a high probability of being 'inconsistent' state. But,after I increase the interval，the 'inconsistent' state no longer appears. 

Not sure if this is related to my restarting the node for other reasons before. I remember I also tried to set different internvals before.

**Comment by tom95858** [comment]
@MAChenliang , The ldms_ls command reports the time it takes the sampler to collect the data. For example:

```
tom@ovs-5416 ~
$ ldms_ls -h orion-01 -p 10001 -a munge -l orion-01/vmstat | head -10
orion-01/vmstat: consistent, last update: Thu Jan 21 12:23:10 2021 -0600 --> [2113us] <--
M u64        component_id                               10001
D u64        job_id                                     0
D u64        app_id                                     0
D u64        nr_free_pages                              3572476
D u64        nr_zone_inactive_anon                      37921
D u64        nr_zone_active_anon                        67603
D u64        nr_zone_inactive_file                      119535
D u64        nr_zone_active_file                        79723
D u64        nr_zone_unevictable                        0
```
In this example,  it took the sampler **2,113 us** to update the metric set's contents. Take a look at that value for you're impisensor sampler and it will let you know what may be reasonable for an update interval at the aggregator.
