### ISSUE TITLE
OVIS_FLEX and OVIS_FLEX_UNION?

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#609]
Can someone describe to me the reason for OVIS_FLEX and OVIS_FLEX_UNION defines in ldmsd_request.h? If anything they seem to serve to make the code harder to read. Just using a zero would have been a lot more clear to me rather than hiding the zero in a define that I have to go look up. And why we need two defines for zero is especially unclear.

**Comment by baallan** [comment]
The reason is changes in ISO C and in gcc support thereof for the flex language feature. 0 and empty get compiled to different things, only one of which is right, in various circumstances.

**Comment by tom95858** [comment]
Hi @morrone, I don't think it has anything to do with an ISO C language feature per-se, it has to do with FORTIFY which you probably know is a gcc extension intended to detect memory object overruns at run-time. 

However, FORTIFY has problems (one might say bugs) when handling flexible array members in structures. In particular: 

```
/* Original K&R method */
struct knr_struct {
   int stuff;
   char name[0];    /* the compiler knows this has zero length */
};

/* Since C99, this is supported */
struct c99_struct {
   int stuff;
   char name[];    /* this compiler knows this has an unknown length */
};
```
The LDMS code all previously used the K&R method, which is not strictly a "language feature", but rather an artifact of __name__ having a valid offset, but zero length. This is used almost ubiquitously in my experience; however it breaks FORTIFY as follows:

The FORTIFY support includes implementations of the C library like strcmp_fortify, strcat_fortify, etc... These versions know that strings and flexible array members, for example, have a prefix that include it's length and will ensure that buffer overruns cause an abort. The compiler replaces calls to __libcfunc__ with calls to __libcfunc__fortify for objects of known length.

The problem is that knr_struct.name[0] is **known** to be zero length while c99_struct.name[] has an **unknown** length. So when FORTIFY is enabled, all of our trailing structure members declared with [0] would cause FORTIFY to generate false errors.

So why not just change everything to the C99 []? Because the older compilers didn't support it.

I personally find the OVIS_FLEX annotations to be grotesque; however, this was the compromise to accommodate those who felt FORTIFY support was mandatory and those who felt <C99 support was mandatory.

It might be worth revisiting whether or not we still care about support for what are now ancient compilers.

**Comment by morrone** [comment]
Thanks! That makes sense.
