### ISSUE TITLE
Sampling Issues For Set Group Members LDMS 4.3.6

### ISSUE THREAD

**Issue by helloSeen** [ovis-hpc/ovis#687]
Hi all, we are using custom procdiskstat samplers on our system to integrate with other services. It is composed of smaller sets in a set group.
As an example:
```
ldms_ls -x sock -p 60002 proc_group
proc_group
procdiskstats-sda
procdiskstats-sda1
procdiskstats-sda2
procdiskstats-sda3
etc...
```
We are aggregating across a few nodes for some systems using a genders configuration. The issue we are facing is that we are getting a combination of "procdiskstats-sda1 oversampled 11117395 == 11117395" and "procdiskstats-sda1: there is an outstanding update" nearly every second for every set group member. We are not seeing these messages for any of the other samplers that do not use set groups.

Our samplers are set to 10 second intervals and our aggregators are set to 10 sec intervals with 5 second offset. If we could get some assistance on this that would be greatly appreciated because right now our aggregator logs are hosed with these messages.

**Comment by tom95858** [comment]
@helloSeen:

The message "...oversampled..." means that the generation number in the set header hasn't changed since the last update completed.

The fact that the message is coming every second implies that your aggregator is requesting an update of the set every second. If your procdiskstats-sd? is configured to be sampled every 10 seconds, and you are updating at the aggregator every second, 9 out of 10 times you will get the oversampled message. That's what the message is telling you.

So my guess is that the group is configured to be updated every second, instead of every 10 seconds.

The message "...there is an outstanding update ..." says that the ldms_xprt_update request is submitted before the previous update completes. There could be a number of reasons this is happening such as a slow network, overworked sampler and/or aggregator.

As a first go, please change the update interval on your group set to 10 seconds.

**Comment by helloSeen** [comment]
Thanks for the quick response @tom95858. It looks like the update hint on the grp_schema was set to 1 second! However, the set group members are set to 10 second intervals. Any reason why the grp_schema set to a different value if we used `ldmsd_interval_default=10000000,ldmsd_offset_default=5000000,ldmsd_port=60002` in the genders config? Second, I am guessing this means the update interval of the grp_schema takes priority over the update interval of each set group member?

Thanks

**Comment by tom95858** [comment]
As you heard in the meeting genders is not recommended. My guess is that it
doesn't work correctly for group sets.

**Comment by tom95858** [comment]
.
| ... Second, I am guessing this means the update interval of the
grp_schema takes priority over the update interval of each set group member?

The update of the group is what triggers the update of the members.

Thanks
