### ISSUE TITLE
ldms_set_delete() does not clean up set_tree entry

### ISSUE THREAD

**Issue by krehm** [ovis-hpc/ovis#7]
As part of its processing, ldms_set_new() calls __record_set(), which adds a RBT entry to set_tree.  The routine ldms_set_delete() does NOT remove that entry from set_tree, so the reference to the metric set is left in set_tree forever even though the set memory has been released.   The easiest way to see this is to do:

load name=abc
config name=abc instance=xyz
term name=abc
load name=abc
config name=abc instance=xyz

The second config command will fail because of the instance name collision with the previous instance of that plugin still in set_tree.  You have to restart the ldmsd daemon in order to reuse that instance name.

Here is a clip from routine ldms_set_delete(), to fix this problem I added the three lines at the end  and it seems to work fine.

@@ -480,6 +480,9 @@ void ldms_set_delete(ldms_set_t s)
                        LIST_REMOVE(rbd, set_link);
                        __ldms_free_rbd(rbd);
                }
 +               rem_local_set(set);
 +               mm_free(set->meta);
 +               free(set);
        }
        __ldms_set_tree_unlock();
        free(sd);

**Comment by tom95858** [comment]
Hi Kevan,
Good catch we'll incorporate this fix.
Tom

**Comment by zongzeliunt** [comment]
Anybody can help me on how to use syslog2balerd.pl? It's urgent! Thanks!

**Comment by opengridcomputing** [comment]
Hi Kevan and Tom,

By design, ldms_set_delete() does not really delete the set. It cleans up the remote buffer descriptors attached to the set and marks the set as unpublished. An unpublished set will not be listed in the dir response.  The reason for this is for preventing race condition on aggregators, especially with multiple producers the set are collected from.

I'm proposing to

1. Rename ldms_set_delete() to something that reflects what it does, e.g., ldms_set_unpublish().
2. Add an API to really delete the set: remove set from the tree and free the set memory. The API will be named ldms_set_delete(). There will be no code changes in any sampler plugin.

Nichamon

**Comment by nichamon** [comment]
I just checked ldms_set_unpublish() already exists with different functionality from the current ldms_set_delete(), so the new name of ldms_set_delete() will be something else. 

More detail on why ldms_set_delete() works this way. According to the commit (cfc80ea3b9f), the problem at the time was that aggregators could read garbage from a producer if the set on the producer had been deleted. The dir del event is delivered after the aggregator read the set memory on the producer.

Nichamon
