### ISSUE TITLE
set lifecycle and L1 problem

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#771]
I have a sampler (pr 767) where  L0 sets have the following lifecycle (driven by events in /proc/$pid):
```
ldms_set_new
ldms_set_publish
ldmsd_set_register
(L1 discovers)
ldmsd_set_deregister
ldms_set_unpublish
ldms_set_delete
```

And at the L1, there seems to be some issue with it never getting properly eliminated; the updtr keeps looking for it forever, as logged below. Notice that the set has an existence shorter than the updater interval (1 sec). I am stumped as to why L1 is lingering on it. Help!

1626913802.534716: INFO      : Adding the metric set 'localhost1/0/1626913802.492302/19019'
1626913803.103245: DEBUG     : updtr_task sched '1000000': set 'localhost1/0/1626913802.492302/19019'
1626913803.145117: INFO      : prdcr localhost1: disappeared (No such file or directory) set in lookup callback of set 'localhost1/0/1626913802.492302/19019'
1626913804.104459: DEBUG     : updtr_task sched '1000000': set 'localhost1/0/1626913802.492302/19019'
1626913804.147541: INFO      : prdcr localhost1: disappeared (No such file or directory) set in lookup callback of set 'localhost1/0/1626913802.492302/19019'
1626913805.101622: DEBUG     : updtr_task sched '1000000': set 'localhost1/0/1626913802.492302/19019'
1626913805.144678: INFO      : prdcr localhost1: disappeared (No such file or directory) set in lookup callback of set 'localhost1/0/1626913802.492302/19019'
1626913806.103705: DEBUG     : updtr_task sched '1000000': set 'localhost1/0/1626913802.492302/19019'
1626913806.146866: INFO      : prdcr localhost1: disappeared (No such file or directory) set in lookup callback of set 'localhost1/0/1626913802.492302/19019'
1626913807.103955: DEBUG     : updtr_task sched '1000000': set 'localhost1/0/1626913802.492302/19019'
1626913807.143999: INFO      : prdcr localhost1: disappeared (No such file or directory) set in lookup callback of set 'localhost1/0/1626913802.492302/19019'
1626913808.102939: DEBUG     : updtr_task sched '1000000': set 'localhost1/0/1626913802.492302/19019'
1626913808.142982: INFO      : prdcr localhost1: disappeared (No such file or directory) set in lookup callback of set 'localhost1/0/1626913802.492302/19019'
1626913809.103190: DEBUG     : updtr_task sched '1000000': set 'localhost1/0/1626913802.492302/19019'
1626913809.146308: INFO      : prdcr localhost1: disappeared (No such file or directory) set in lookup callback of set 'localhost1/0/1626913802.492302/19019'

**Comment by baallan** [comment]
based on the symptoms and following the source, at the L1 the prdcr_set gets stuck in LDMSD_PRDCR_SET_STATE_START if it disappears from L0 before it ever leaves the START state on L1.
Trying to further analyze the source and trace the delivery of the set_delete event from L0 to understand why it's stuck.

**Comment by baallan** [comment]
Updating __ldmsd_prdset_lookup_cb to change prd_set->state to LDMSD_PRDCR_SET_STATE_DELETED in the case of lookup status == ENOENT, suppresses the further issuing of error messages, but doesn't get the offending dangling prd_set out of the list maintained inside  'ldmsd_prdcr_t prdcr'. What's the right scope to check for LDMSD_PRDCR_SET_STATE_DELETED and prune the prd_set from the list?

@narategithub @tom95858 any clues on the right way to prune after DELETED has happened? We seem to deal ok with a whole producer disappearing, but not with a set disappearing while it is still in the START state.

**Comment by tom95858** [comment]
@baallan there is probably a bug wherein the updater doesn't get scheduled before the set is deleted. But that is just a theory. It seems like you could create a simple test case in Python to trigger this so that we can debug it.

**Comment by baallan** [comment]
@tom95858 this is only happening on a few sets of many , so the test case isn't so simple to reproduce. Will look further into how to force the timing.

**Comment by nichamon** [comment]
@tom95858  @baallan I found out why L1 does not clean up the set and keeps looking it up. The timeline is as follows.

L0: create set A
L0: publish set A
L1: receive dir_add
L0: unpublish set A
L0: delete set A. L0 does _not_ send the SET_DELETE message to L1 because the set has not been looked up yet.
L1: lookup set A
L0: Receive the lookup request for set A but set A is not in the set tree or the free set tree anymore

**Comment by nichamon** [comment]
@tom95858 I told you on the phone that the bug has some things to do with a missing RBD. I was wrong. This has nothing to do with the existence of RBDs. The client registers on a set at the lookup time. Suppose the server deletes the set before it receives a client's lookup request. There is no map between the set and the client. However, the `dir` logic can handle this. I'm thinking of reviving `dir_del` by making it sending the SET_DELETE message to clients instead of `ldms_set_delete`. Server calls to `ldms_set_unpublish()` triggers a `dir_del` message to clients. When the server calls `ldms_set_unpublish()`, no clients will see the set, so any clients with the set handle should delete it.

**Comment by baallan** [comment]
@nichamon thank you for confirming the issue.
