### ISSUE TITLE
a question about __ldms_remote_update

### ISSUE THREAD

**Issue by krehm** [ovis-hpc/ovis#8]
While reading code I came across something that I didn't understand, that may or may not be a bug.  I don't have the bandwidth to pursue this right now, could someone take a look and comment on it?

Suppose that a sampler makes a change to the metadata portion of a metric set, and updates meta_gn in both the metadata and data sections of the set in its memory.

The aggregator will call update_data -> do_update -> ldms_xprt_update -> __ldms_remote_update in order to download the sampler's latest metric set.  The code tries to figure out whether it has to download the entire set, or just the data portion.

It looks to me like the code near the top of the routine is reading the meta_gn values out of the PREVIOUS metric set that it received from the sampler.   Do I have this right?   In that previous sample, the two (older) meta_gn values matched, and so the aggregator is only going to call do_read_data() to get the data portion of the next metric set.  So when this metric set is processed, it will have a metadata portion with an old meta_gn paired with a data portion with a newer meta_gn.

The next time that __ldms_remote_update gets called, it will see that the two meta_gn values don't match, and it will pull down both metadata and data portions, so the problem resolves itself in the subsequent sample, but there is that one sample in which there is a meta_gn mismatch.  I suspect that's an issue, but I don't know how serious it is.  If it's not a big deal, just close this.

**Comment by tom95858** [comment]
Sorry for the delay, I was out of town and then I had to page all of this in.

There are three design goals that led to this design behavior:
1. Reduce the number of memory registrations. Allocating the data contiguous with the meta data allows a single memory registration to handle both regions.
2. Reduce the number of RDMA_READ operations required to fetch the data.
3. Protect the aggregator from being 'hung' by a rogue sampler.

 If we don't care about 2, we can read the data, compare the data->meta_gn, and if not equal, submit another RDMA_READ of the meta data. This has at-least two negative consequences:
1. A rogue sampler can hang the aggregator and consume significant network bandwidth by simply constantly changing any ldms_meta_metric in the set. Then as as each read completes, the meta_gn's wouldn't match triggering another read and so-on in a loop.
2. It requires 2 reads to get the data+meta data.
3. It puts the sampler, indirectly, in charge of controlling update frequency as described

So this was the simplest (acknowledging that there are ways to rate-limit for 3) way to address the above and is thought to be sufficient given the assumption that the meta-data is changed infrequently as compared to the sample rate.

Hope this helps,
Tom

**Comment by krehm** [comment]
Okay, sounds good.   My concern was that somehow a store might get confused if it was looking at a data portion of a set that didn't match its metadata portion, for that one sample.  I assumed, perhaps wrongly, that a store would never bother to compare the meta_gn values itself because the updtr was responsible for that.  Sounds like it's no big deal, want me to close this?

**Comment by oceandlr** [comment]
One of the things that came up in the last discussion was that the current implementation of the csv store gets the headers only once for a particular schema. So it is true that for this current implementation that the metadata would not be checked for a change.  However, this is an artifact due to the implementation which is just that way because it its innards were copied over from v2, which had a more limited interface to the store() and config(). It hasnt been updated a) due to lack of time and b) because the main use case for the consumers has been a desire for a consistent set of values so they could count on using the same database table or csv processing for the output.

Relatedly some samplers, like those that need to support a change to hyper threading, have an interface that allows you to specify the maximum number of values that might be reported and so either a full set of values or a smaller set padded with zeros is reported. It would be a reasonable change to be able to support in the samplers and the store both a) the fixed number of entries and b) the flexible number of entries.

**Comment by tom95858** [comment]
The kinds of things that you are allowed to do to a set once it is created is very limited. IOW, you can't add or delete metrics of a set once it is created; but you can change some of the attributes of a metric, for example, it's user-data field. The user-data field was put there to allow an application to associate information with the metric that was application specific. If this value is changed, the meta_gn would get bumped so it would be fetched when modified.

Later, we added meta-metrics. These are metrics were conceived of  to handle this same kind-of problems, i.e. provide semi-static information about the machine on which the set was gathered that would only be fetched when it was modified, for example, component_id, job_id, etc... 

All that said, the metric_id, metric_name, etc... can't change once the set is created, therefore, the stores that save those metrics can't get 'confused' because the things that might confuse it can't change.

**Comment by tom95858** [comment]
Hi @krehm yes, I think you can close this if you are satisfied with the answer.

**Comment by krehm** [comment]
It appears that all is working as designed, thanks.   By the way, if this is not the correct venue for raising issues, let me know.
