### ISSUE TITLE
dstat sampler does not include sysconf(_SC_CLK_TCK)

### ISSUE THREAD

**Issue by tom95858** [ovis-hpc/ovis#843]
@baallan, I think the utime, stime, xxtime metrics are all in clock ticks and can only be interpreted if you know the sysconf(_SC_CLK_TCK) value. Could you please either include this value in the metric set or alternatively do the division yourself in the sampler? I _think_ the later is preferred since the value can change due to CPU throttling, but I'm open to either. What do you think?

**Comment by tom95858** [comment]
@baallan, it also looks like fd_max is less than fd_count which I don't think should ever be the case...

**Comment by tom95858** [comment]
@baallan, here's an example gathered on one of our clusters...
    dsosql: select fd_count, fd_max from dstat_37 where component_id == 600001 and timestamp > 1639102418                                                                                                                                 
    ORDER_BY "component_id", "timestamp", "job_id"                                                                                                                                                                         
    fd_count           fd_max             component_id       timestamp                        job_id                                                                                                                        
    ------------------ ------------------ ------------------ -------------------------------- ------------------                                                                                                          
                29                 28             600001                1639102440.001488           11790052                                                                                                          
                28                 27             600001                1639102500.000692           11790052

**Comment by baallan** [comment]
@tom95858 I will take a look at dstat. All the hpc systems I've looked at since 2014 have tick at 100Hz, but that's no guarantee of anything going forward.

**Comment by baallan** [comment]
the same problem exists for the other proc files reporting ticks.

**Comment by baallan** [comment]
@tom95858 re: tick/sec value: my inclination is to add the sc_clk_tck metametric column since changing the definition of the existing tick metrics will break downstream column type definitions.  I will poke around and see what other stores need scclktck. 

I have never managed to find any documentation saying that the sysconf kernel scheduler tick varies with throttling. It seems to be tied to config_hz instead and (in glibc) stored as an integer constant. Thus i would make it a metadata metric. 

It would also be possible to add an option to the dstat sampler (since it already has metric  subgroups) to add a group of the scaled times. The only question there is what to scale time to as a u64, since FP is lossy (64 bits vs 53 bits with holes down where we calculate differences); seconds? centiseconds? milliseconds?  microseconds? I think the answers to time precision are multi-valued enough that they should be left to a configurable function store/transform plugin or other store plugin or analysis code rather than hard coded in the samplers.

**Comment by baallan** [comment]
@tom95858 fd's initially number from 0 upward [e.g. (0,1,2) with a count of 3]. That eventually will develop holes such that fd_max > fd_count as additional 'files' are opened/closed.

**Comment by tom95858** [comment]
@baallan Ok, I see this is the maximum fd number, not the max number of open fd. That number is max_fd + 1. Thanks for the explanation.
